name = "EconoSim"
uuid = "cc8cb6e0-4c11-4d04-b964-59e7aacda730"
authors = ["Stef Kuypers <stef@happonomy.org>"]
version = "0.2.1"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FixedPointDecimals = "fb4d412d-6eee-574d-9565-ede6634db7b0"
Intervals = "d8418881-c3e1-53bb-8760-2df7ec849ed5"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
PkgAuthentication = "4722fa14-9d28-45f9-a1e2-a38605bd88f0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Todo = "b28a226c-6cff-11e9-1336-699fd753ab00"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
DataStructures = "0.18"
PkgAuthentication = "2.0.3"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
